version: 0.0
os: windows
files:
  - source: \
    destination: c:\temp\codedeploy_test_programs
hooks:
  BeforeInstall:
    - location:
  AfterInstall:
    - location: Scripts/RunResourceTests.sh
      timeout: 180
  ApplicationStart:
    - location: Scripts/RunFunctionalTests.sh
      timeout: 3600
  ValidateService:
    - location: Scripts/MonitorService.sh
      timeout: 3600